### ISSUE TITLE
Streamline setting up a new instance

### ISSUE THREAD

**Issue by anandology** [pipalacademy/pipalhub#4]
Right now, it takes too many steps to setup a new instance of pipalhub. We need to make it into a couple of steps.

Adding users and installing custom packages is out of scope for this issue.

## Proposed Approach

Assuming that you have created a new server and logged into it as root.

Assume that the node is Ubuntu 22.04.

```
$ curl https://github.com/..../setup-node.sh -o /tmp/setup-node.sh
$ bash /tmp/setup-node.sh lab.pipal.in
```

This would setup everything and the server would be ready to use.

**Improvement 1**

We could supply those two lines as initialization script (userdata) when creating a new node so that we don't have to run that manually.

**Improvement 2**

Create a create-node.py that takes DIGITALOCEAN_TOKEN from env and creates a new node of given size and hostname.

This is run from any developers node.

```
$ export DIGITALOCEAN_TOKEN=abcd1234
$ python create-node.py --hostname lab.pipal.in --instance-size small|medium|large
```

This should add all the ssh-keys in the account to the node.

This should also create a DNS record for the hostname.

**Comment by nikochiko** [comment]
This is done. Commits: https://github.com/pipalacademy/pipalhub/commit/3871d55341daa0b1891938f15da45ffc82027a11 and https://github.com/pipalacademy/pipalhub/commit/57659f0558f183b7627aeb0991bc759fbd9f6de9
